version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "19000:19000"
      - "19001:19001"
    volumes:
      - .:/home/app
    command: "yarn start"
    restart: always