FROM node:latest




ENV ADB_IP="192.168.112.101"
ENV REACT_NATIVE_PACKAGER_HOSTNAME="192.168.1.1"
EXPOSE 3000
EXPOSE 19000
EXPOSE 19001

RUN apt-get update -y && \
    apt-get install android-tools-adb -y
RUN yarn add lerna --global

WORKDIR /usr/src/app
RUN npm i lerna -g --loglevel notice
COPY . .

COPY lerna.json .
RUN lerna bootstrap
